const markets={
 tw:{marketLabel:'台灣加權',indexValue:'22,510.25',indexChange:'+1.18%',turnover:'4,238 億',breadth:'623 / 338',foreignFlow:'+126.8 億',temperature:'偏多 72°',symbol:'2330',company:'台積電',summary:'趨勢與籌碼共振，短線拉回仍具承接力道。',price:'1,045.00',priceMove:'▲ 18.00 · 1.75%',score:82,grade:'A',signal:'偏多',support:'980.00',resistance:'1,080.00',volatility:'22.6%',strategy:'拉回分批布局',entry:'1,000 – 1,025',riskRule:'停損 960 · 目標 1,150',instTotal:'+184 億',concentration:'68%',riskScore:34,riskBadge:'中低',verdict:'回檔承接，不追高',verdictNote:'指數維持多頭結構，但高檔震盪加劇。優先選擇趨勢完整、法人連續買超且接近支撐的標的。',scores:[88,84,76,79,71,86],decisions:[['趨勢判斷','強勢多頭',88],['籌碼狀態','法人偏多',82],['技術位置','接近支撐',76],['量價結構','健康',84]],risks:[['波動風險',38],['估值壓力',52],['籌碼鬆動',24],['大盤系統性',31]],flow:[[76,35],[92,44],[67,30],[105,48],[88,42]],stocks:[['2454','聯發科','1,425','+2.15%',89],['2317','鴻海','212','+1.44%',85],['2382','廣達','318','+0.95%',81],['2308','台達電','398','+1.79%',78]],series:[35,37,34,41,39,46,52,58,55,67,72,78,75,84,91,104,98,112,126,118,139,145,137,151,160,153,169,176,165,182]},
 us:{marketLabel:'S&P 500',indexValue:'6,214.68',indexChange:'+0.62%',turnover:'US$ 486B',breadth:'327 / 176',foreignFlow:'+US$ 3.8B',temperature:'偏多 68°',symbol:'NVDA',company:'NVIDIA',summary:'AI 需求延續，價格守穩中期均線但短線波動升高。',price:'187.62',priceMove:'▲ 2.41 · 1.30%',score:78,grade:'A−',signal:'偏多',support:'178.00',resistance:'195.00',volatility:'35.8%',strategy:'突破確認後布局',entry:'179 – 184',riskRule:'停損 171 · 目標 208',instTotal:'+US$ 2.4B',concentration:'64%',riskScore:43,riskBadge:'中等',verdict:'守支撐續抱，突破加碼',verdictNote:'大型科技股動能仍在，但利率與財報預期造成震盪。控制部位，優先觀察成交量是否同步放大。',scores:[84,80,69,75,66,79],decisions:[['趨勢判斷','中期偏多',84],['機構資金','持續流入',78],['技術位置','區間上緣',69],['量價結構','尚可',75]],risks:[['波動風險',56],['估值壓力',63],['資金退潮',32],['利率敏感',46]],flow:[[64,42],[88,55],[73,49],[96,61],[82,54]],stocks:[['MSFT','Microsoft','527.18','+0.84%',86],['AVGO','Broadcom','348.50','+1.62%',84],['GOOGL','Alphabet','252.11','+0.76%',80],['META','Meta','778.42','+1.08%',77]],series:[42,46,43,49,54,51,58,64,60,67,73,70,79,85,82,91,96,88,101,108,104,116,121,112,127,133,129,141,146,139]}
};
let current='tw';
const $=id=>document.getElementById(id);
function linePath(points,w=780,h=230,pad=18){const min=Math.min(...points),max=Math.max(...points);return points.map((v,i)=>`${i?'L':'M'} ${(i/(points.length-1)*w+20).toFixed(1)} ${(h-(v-min)/(max-min)*h+pad).toFixed(1)}`).join(' ')}
function movingAvg(a,n){return a.map((_,i)=>{const s=a.slice(Math.max(0,i-n+1),i+1);return s.reduce((x,y)=>x+y,0)/s.length})}
function drawPrice(d){const svg=$('priceChart'),s=d.series,m5=movingAvg(s,4),m20=movingAvg(s,9);let grid='';for(let i=0;i<6;i++)grid+=`<line x1="20" y1="${22+i*44}" x2="800" y2="${22+i*44}" stroke="#202a40" stroke-width="1"/>`;let bars=s.map((v,i)=>{const x=20+i*(780/(s.length-1));const bh=12+((i*17)%42);return `<rect x="${x-3}" y="${284-bh}" width="6" height="${bh}" fill="${i&&s[i]>=s[i-1]?'#56e09b':'#ff6b72'}" opacity=".35"/>`}).join('');svg.innerHTML=`<defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#56e09b" stop-opacity=".28"/><stop offset="1" stop-color="#56e09b" stop-opacity="0"/></linearGradient></defs>${grid}<path d="${linePath(s)} L 800 270 L 20 270 Z" fill="url(#area)"/><path d="${linePath(s)}" fill="none" stroke="#56e09b" stroke-width="3"/><path d="${linePath(m5)}" fill="none" stroke="#7aa2ff" stroke-width="1.8"/><path d="${linePath(m20)}" fill="none" stroke="#f6c960" stroke-width="1.5" stroke-dasharray="5 5"/>${bars}<circle cx="800" cy="${(248-(s.at(-1)-Math.min(...s))/(Math.max(...s)-Math.min(...s))*230).toFixed(1)}" r="5" fill="#56e09b" stroke="#07101b" stroke-width="3"/>`}
function drawRadar(d){const svg=$('radarChart'),cx=180,cy=128,r=92,labels=['趨勢','籌碼','動能','量價','估值','風險'];const pts=(rad,vals=labels.map(()=>100))=>labels.map((_,i)=>{const a=-Math.PI/2+i*Math.PI/3;return `${cx+Math.cos(a)*rad*(vals[i]/100)},${cy+Math.sin(a)*rad*(vals[i]/100)}`}).join(' ');let rings=[.25,.5,.75,1].map(x=>`<polygon points="${pts(r*x)}" fill="none" stroke="#26324b"/>`).join('');let axes=labels.map((l,i)=>{const a=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r,tx=cx+Math.cos(a)*(r+25),ty=cy+Math.sin(a)*(r+25);return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#26324b"/><text x="${tx}" y="${ty}" text-anchor="middle" dominant-baseline="middle" fill="#8996b2" font-size="11">${l}</text>`}).join('');svg.innerHTML=`${rings}${axes}<polygon points="${pts(r,d.scores)}" fill="#7aa2ff33" stroke="#7aa2ff" stroke-width="2"/>${d.scores.map((v,i)=>{const a=-Math.PI/2+i*Math.PI/3;return `<circle cx="${cx+Math.cos(a)*r*v/100}" cy="${cy+Math.sin(a)*r*v/100}" r="3.5" fill="#56e09b"/>`}).join('')}`}
function render(key){current=key;const d=markets[key];document.querySelectorAll('.tab').forEach(b=>{const on=b.dataset.market===key;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)});['marketLabel','indexValue','indexChange','turnover','breadth','foreignFlow','temperature','symbol','company','summary','price','priceMove','score','grade','signal','support','resistance','volatility','strategy','entry','riskRule','instTotal','concentration','riskScore','riskBadge','verdict','verdictNote'].forEach(id=>$(id).textContent=d[id]);$('scoreRing').style.background=`conic-gradient(var(--green) 0 ${d.score}%,#222c42 ${d.score}%)`;$('decisionList').innerHTML=d.decisions.map(x=>`<div class="decision-item"><span>${x[0]}</span><div class="meter"><i style="width:${x[2]}%"></i></div><b>${x[1]}</b></div>`).join('');$('riskList').innerHTML=d.risks.map(x=>`<div class="risk-row"><span>${x[0]}</span><div class="meter"><i style="width:${x[1]}%"></i></div><b>${x[1]}%</b></div>`).join('');$('flowChart').innerHTML=d.flow.map((x,i)=>`<div class="flow-col"><i class="flow-pos" style="height:${x[0]}%"></i><i class="flow-neg" style="height:${x[1]}%"></i><small>D${i+1}</small></div>`).join('');$('watchlist').innerHTML=d.stocks.map(x=>`<div class="stock-row"><div class="stock-name"><b>${x[0]}</b><small>${x[1]}</small></div><span>${x[2]}</span><span class="up">${x[3]}</span><span class="score-pill">${x[4]}</span></div>`).join('');drawPrice(d);drawRadar(d)}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>render(b.dataset.market)));document.querySelectorAll('.range-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.range-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('toast').textContent=`已切換為 ${b.textContent} 區間`;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1600)}));$('refresh').addEventListener('click',()=>{$('refresh').animate([{transform:'rotate(0)'},{transform:'rotate(360deg)'}],{duration:500})});setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('zh-TW',{hour12:false})},1000);render('tw');

const yahooBase='https://query1.finance.yahoo.com/v8/finance/chart/';
function setFeed(text,state='loading'){$('feedStatus').textContent=text;$('feedStatus').className=`feed-pill ${state}`;$('dataStatus').textContent=state==='error'?'報價連線異常':text;$('dataPulse').style.background=state==='error'?'var(--red)':state==='loading'?'var(--amber)':'var(--green)'}
function yahooSymbol(raw,market){const s=raw.trim().toUpperCase();return market==='tw'&&!s.includes('.')?`${s}.TW`:s}
async function getYahoo(symbol){const url=`${yahooBase}${encodeURIComponent(symbol)}?interval=5m&range=5d&includePrePost=false`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`Yahoo ${res.status}`);const result=(await res.json()).chart?.result?.[0];if(!result)throw new Error('Yahoo 無資料');return result}
async function getTwse(code){const res=await fetch('https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL',{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`TWSE ${res.status}`);const rows=await res.json();const row=rows.find(x=>String(x.Code)===code);if(!row)throw new Error('證交所查無代號');return row}
function applyQuote(result,market,raw,twse){const meta=result.meta||{},quotes=result.indicators?.quote?.[0]||{};const closes=(quotes.close||[]).filter(Number.isFinite);const live=Number(meta.regularMarketPrice??closes.at(-1));const prev=Number(meta.chartPreviousClose??meta.previousClose??closes.at(-2));if(!Number.isFinite(live))throw new Error('報價欄位缺失');const delta=live-prev,pct=prev?delta/prev*100:0,d=markets[market];d.symbol=raw.toUpperCase();d.company=twse?.Name||meta.longName||meta.shortName||d.company;d.price=live.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});d.priceMove=`${delta>=0?'▲':'▼'} ${Math.abs(delta).toFixed(2)} · ${Math.abs(pct).toFixed(2)}%`;d.series=closes.length>10?closes.slice(-60):d.series;d.support=(live*.95).toFixed(2);d.resistance=(live*1.05).toFixed(2);const hi=Number(meta.regularMarketDayHigh),lo=Number(meta.regularMarketDayLow);if(Number.isFinite(hi)&&Number.isFinite(lo)&&live)d.volatility=`${((hi-lo)/live*100).toFixed(2)}% 日內`;render(market);$('priceMove').className=delta>=0?'up':'down';$('indexChange').className=pct>=0?'up':'down';$('lastUpdated').textContent=`更新 ${new Date((meta.regularMarketTime||Date.now()/1000)*1000).toLocaleString('zh-TW',{hour12:false})}`;const googleMarket=market==='tw'?'TPE':'NASDAQ';$('googleLink').href=`https://www.google.com/finance/quote/${encodeURIComponent(raw.toUpperCase())}:${googleMarket}`}
async function updateIndex(market){try{const symbol=market==='tw'?'%5ETWII':'%5EGSPC',r=await getYahoo(symbol),m=r.meta||{},now=Number(m.regularMarketPrice),prev=Number(m.chartPreviousClose||m.previousClose),pct=(now-prev)/prev*100;$('indexValue').textContent=now.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});$('indexChange').textContent=`${pct>=0?'+':''}${pct.toFixed(2)}%`;$('indexChange').className=pct>=0?'up':'down'}catch(e){console.warn('Index quote unavailable',e)}}
async function loadQuote(raw=$('symbolInput').value){const market=current,clean=raw.trim().toUpperCase();if(!/^[A-Z0-9.^-]{1,12}$/.test(clean)){setFeed('代號格式錯誤','error');return}$('symbolInput').value=clean;setFeed('正在取得報價…','loading');$('quoteSearch').setAttribute('aria-busy','true');try{const yPromise=getYahoo(yahooSymbol(clean,market));const twPromise=market==='tw'?getTwse(clean).catch(()=>null):Promise.resolve(null);const [quote,twse]=await Promise.all([yPromise,twPromise]);applyQuote(quote,market,clean,twse);setFeed(market==='tw'?(twse?'Yahoo 延遲報價 · 證交所核對':'Yahoo Finance 延遲報價'):'Yahoo Finance 延遲報價','delayed');$('toast').textContent='市場報價已更新';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1600);updateIndex(market)}catch(err){console.error(err);setFeed('暫時無法取得報價','error');$('lastUpdated').textContent='保留最近顯示資料'}finally{$('quoteSearch').removeAttribute('aria-busy')}}
$('quoteSearch').addEventListener('submit',e=>{e.preventDefault();loadQuote()});document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{const symbol=b.dataset.market==='tw'?'2330':'NVDA';$('symbolInput').value=symbol;loadQuote(symbol)}));$('refresh').addEventListener('click',()=>loadQuote());loadQuote('2330');setInterval(()=>loadQuote(),60000);
